# Generated by Django 5.1.1 on 2024-11-07 12:49

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='name')),
                ('name_ka', models.CharField(max_length=255, null=True, unique=True, verbose_name='name')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date creation')),
            ],
            options={
                'verbose_name': 'product tag',
                'verbose_name_plural': 'produtc tags',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='name')),
                ('name_ka', models.CharField(max_length=255, null=True, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('slug_en', models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug')),
                ('slug_ka', models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ka', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='image')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date creation')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='store.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='name')),
                ('name_ka', models.CharField(max_length=255, null=True, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('slug_en', models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug')),
                ('slug_ka', models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ka', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='price')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='quantity')),
                ('weight', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='weight')),
                ('origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='origin')),
                ('origin_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='origin')),
                ('origin_ka', models.CharField(blank=True, max_length=255, null=True, verbose_name='origin')),
                ('quality', models.CharField(blank=True, max_length=255, null=True, verbose_name='quality')),
                ('quality_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='quality')),
                ('quality_ka', models.CharField(blank=True, max_length=255, null=True, verbose_name='quality')),
                ('healthy', models.BooleanField(default=True, verbose_name='healthy')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('image', models.ImageField(upload_to='products/', verbose_name='image')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date creation')),
                ('category', models.ManyToManyField(related_name='products', to='store.category', verbose_name='category')),
                ('tag', models.ManyToManyField(related_name='products', to='store.producttag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
